### ISSUE TITLE
Keyboard constants

### ISSUE THREAD

**Issue by drhayes** [rcolinray/phaser-dash-docset#6]
Here's a forum post if you don't want to pull them from the source: http://www.html5gamedevs.com/topic/10139-phaser-keyboard-codes-cheatsheet/

**Comment by rcolinray** [comment]
I think this issue would more easily be addressed in the phaser repo. My script parses the phaser documentation, so if they update the documentation to include the shortcuts, then it will automatically be pulled in to the Dash docset.
